default:
  auroraai_host: http://localhost:8000
  profile_management_api_url: http://profile-management-api
  instance1_config:
    mock_service_port: '8000'
    client_id: 708cfe6c-a099-47fc-b77e-102957a6b696
    stored_attributes:
    - municipality_code
    - age
    remote_attributes:
    - life_situation_meters
  instance2_config:
    mock_service_port: '8001'
    client_id: 263e4888-5f72-4400-83ec-2261843c1b05
    stored_attributes:
    - life_situation_meters
    remote_attributes:
    - municipality_code
    - age
local:
  profile_management_api_url: http://localhost:7000
localcluster:
  auroraai_host: http://localhost:8080
  jwt_audience: http://router:8080
  profile_management_api_url: http://profile-management-api:7000
