DELETE FROM service_recommender.service_vectors;
DELETE FROM service_recommender.recommendation_service_feedback;
DELETE FROM service_recommender.recommendation_service;
DELETE FROM service_recommender.service;

DELETE FROM service_recommender.recommendation_feedback;
DELETE FROM service_recommender.recommendation;
