CREATE TYPE translatable_text AS (
    "fi" text,
    "sv" text,
    "en" text
);

CREATE TABLE aurora_ai_service_type (
    "id" SERIAL PRIMARY KEY,
    "type" translatable_text NOT NULL
);

INSERT INTO aurora_ai_service_type ("id", "type")
VALUES
    (1, ROW('Verkkoasiointi', 'E-tjänst', 'E-service')),
    (2, ROW('Puhelinasiointi', 'Telefonservice', 'Telephone service')),
    (3, ROW('Lomake', 'Blankett', 'Form')),
    (4, ROW('Palvelupaikka', 'Serviceställen', 'Service location')),
    (5, ROW('Linkit', 'Ytterligare information', 'Addtional information'));

CREATE TABLE aurora_ai_service_location (
    "code" text PRIMARY KEY,
    "location" translatable_text NOT NULL
);

/*
 * Two-digit and three-digit locations are from the "Kunnat" code list:
 * https://koodistot.suomi.fi/codescheme;registryCode=jhs;schemeCode=kunta_1_20210101
 * One-digit locations are from the "Suuralueet" code list:
 * https://koodistot.suomi.fi/codescheme;registryCode=jhs;schemeCode=suuralue_1_20210101
 * Negative locations are special and are not from any code list.
 * Generally, the more digits, the more specific the location is and vice versa.
 */
INSERT INTO aurora_ai_service_location ("code", "location")
VALUES
    ('-1', ROW('Koko Suomi', 'Hela Finland', 'Whole Finland')),
    ('-2', ROW('Koko Suomi (ei Ahvenanmaa)', 'Hela Finland (utom Åland)', 'Whole Finland (except Åland)')),
    ('1', ROW('Helsinki-Uusimaa', 'Helsingfors - Nyland', 'Helsinki-Uusimaa')),
    ('2', ROW('Etelä-Suomi', 'Södra Finland', 'Southern Finland')),
    ('3', ROW('Länsi-Suomi', 'Västra Finland', 'Western Finland')),
    ('4', ROW('Pohjois- ja Itä-Suomi', 'Norra och Östra Finland', 'Northern and Eastern Finland')),
    ('5', ROW('Ahvenanmaa', 'Åland', 'Åland')),
    ('01', ROW('Uusimaa', 'Nyland', 'Uusimaa')),
    ('02', ROW('Varsinais-Suomi', 'Egentliga Finland', 'Southwest Finland')),
    ('04', ROW('Satakunta', 'Satakunta', 'Satakunta')),
    ('05', ROW('Kanta-Häme', 'Egentliga Tavastland', 'Kanta-Häme')),
    ('06', ROW('Pirkanmaa', 'Birkaland', 'Pirkanmaa')),
    ('07', ROW('Päijät-Häme', 'Päijänne-Tavastland', 'Päijät-Häme')),
    ('08', ROW('Kymenlaakso', 'Kymmenedalen', 'Kymenlaakso')),
    ('09', ROW('Etelä-Karjala', 'Södra Karelen', 'South Karelia')),
    ('10', ROW('Etelä-Savo', 'Södra Savolax', 'South Savo')),
    ('11', ROW('Pohjois-Savo', 'Norra Savolax', 'North Savo')),
    ('12', ROW('Pohjois-Karjala', 'Norra Karelen', 'North Karelia')),
    ('13', ROW('Keski-Suomi', 'Mellersta Finland', 'Central Finland')),
    ('14', ROW('Etelä-Pohjanmaa', 'Södra Österbotten', 'South Ostrobothnia')),
    ('15', ROW('Pohjanmaa', 'Österbotten', 'Ostrobothnia')),
    ('16', ROW('Keski-Pohjanmaa', 'Mellersta Österbotten', 'Central Ostrobothnia')),
    ('17', ROW('Pohjois-Pohjanmaa', 'Norra Österbotten', 'North Ostrobothnia')),
    ('18', ROW('Kainuu', 'Kajanaland', 'Kainuu')),
    ('19', ROW('Lappi', 'Lappland', 'Lapland')),
    ('21', ROW('Ahvenanmaa', 'Åland', 'Åland')),
    ('005', ROW('Alajärvi', 'Alajärvi', 'Alajärvi')),
    ('009', ROW('Alavieska', 'Alavieska', 'Alavieska')),
    ('010', ROW('Alavus', 'Alavo', 'Alavus')),
    ('016', ROW('Asikkala', 'Asikkala', 'Asikkala')),
    ('018', ROW('Askola', 'Askola', 'Askola')),
    ('019', ROW('Aura', 'Aura', 'Aura')),
    ('020', ROW('Akaa', 'Ackas', 'Akaa')),
    ('035', ROW('Brändö', 'Brändö', 'Brändö')),
    ('043', ROW('Eckerö', 'Eckerö', 'Eckerö')),
    ('046', ROW('Enonkoski', 'Enonkoski', 'Enonkoski')),
    ('047', ROW('Enontekiö', 'Enontekis', 'Enontekiö')),
    ('049', ROW('Espoo', 'Esbo', 'Espoo')),
    ('050', ROW('Eura', 'Eura', 'Eura')),
    ('051', ROW('Eurajoki', 'Euraåminne', 'Eurajoki')),
    ('052', ROW('Evijärvi', 'Evijärvi', 'Evijärvi')),
    ('060', ROW('Finström', 'Finström', 'Finström')),
    ('061', ROW('Forssa', 'Forssa', 'Forssa')),
    ('062', ROW('Föglö', 'Föglö', 'Föglö')),
    ('065', ROW('Geta', 'Geta', 'Geta')),
    ('069', ROW('Haapajärvi', 'Haapajärvi', 'Haapajärvi')),
    ('071', ROW('Haapavesi', 'Haapavesi', 'Haapavesi')),
    ('072', ROW('Hailuoto', 'Karlö', 'Hailuoto')),
    ('074', ROW('Halsua', 'Halso', 'Halsua')),
    ('075', ROW('Hamina', 'Fredrikshamn', 'Hamina')),
    ('076', ROW('Hammarland', 'Hammarland', 'Hammarland')),
    ('077', ROW('Hankasalmi', 'Hankasalmi', 'Hankasalmi')),
    ('078', ROW('Hanko', 'Hangö', 'Hanko')),
    ('079', ROW('Harjavalta', 'Harjavalta', 'Harjavalta')),
    ('081', ROW('Hartola', 'Gustav Adolfs', 'Hartola')),
    ('082', ROW('Hattula', 'Hattula', 'Hattula')),
    ('086', ROW('Hausjärvi', 'Hausjärvi', 'Hausjärvi')),
    ('090', ROW('Heinävesi', 'Heinävesi', 'Heinävesi')),
    ('091', ROW('Helsinki', 'Helsingfors', 'Helsinki')),
    ('092', ROW('Vantaa', 'Vanda', 'Vantaa')),
    ('097', ROW('Hirvensalmi', 'Hirvensalmi', 'Hirvensalmi')),
    ('098', ROW('Hollola', 'Hollola', 'Hollola')),
    ('102', ROW('Huittinen', 'Vittis', 'Huittinen')),
    ('103', ROW('Humppila', 'Humppila', 'Humppila')),
    ('105', ROW('Hyrynsalmi', 'Hyrynsalmi', 'Hyrynsalmi')),
    ('106', ROW('Hyvinkää', 'Hyvinge', 'Hyvinkää')),
    ('108', ROW('Hämeenkyrö', 'Tavastkyro', 'Hämeenkyrö')),
    ('109', ROW('Hämeenlinna', 'Tavastehus', 'Hämeenlinna')),
    ('111', ROW('Heinola', 'Heinola', 'Heinola')),
    ('139', ROW('Ii', 'Ijo', 'Ii')),
    ('140', ROW('Iisalmi', 'Idensalmi', 'Iisalmi')),
    ('142', ROW('Iitti', 'Itis', 'Iitti')),
    ('143', ROW('Ikaalinen', 'Ikalis', 'Ikaalinen')),
    ('145', ROW('Ilmajoki', 'Ilmola', 'Ilmajoki')),
    ('146', ROW('Ilomantsi', 'Ilomants', 'Ilomantsi')),
    ('148', ROW('Inari', 'Enare', 'Inari')),
    ('149', ROW('Inkoo', 'Ingå', 'Ingå')),
    ('151', ROW('Isojoki', 'Storå', 'Isojoki')),
    ('152', ROW('Isokyrö', 'Storkyro', 'Isokyrö')),
    ('153', ROW('Imatra', 'Imatra', 'Imatra')),
    ('165', ROW('Janakkala', 'Janakkala', 'Janakkala')),
    ('167', ROW('Joensuu', 'Joensuu', 'Joensuu')),
    ('169', ROW('Jokioinen', 'Jockis', 'Jokioinen')),
    ('170', ROW('Jomala', 'Jomala', 'Jomala')),
    ('171', ROW('Joroinen', 'Jorois', 'Joroinen')),
    ('172', ROW('Joutsa', 'Joutsa', 'Joutsa')),
    ('176', ROW('Juuka', 'Juga', 'Juuka')),
    ('177', ROW('Juupajoki', 'Juupajoki', 'Juupajoki')),
    ('178', ROW('Juva', 'Juva', 'Juva')),
    ('179', ROW('Jyväskylä', 'Jyväskylä', 'Jyväskylä')),
    ('181', ROW('Jämijärvi', 'Jämijärvi', 'Jämijärvi')),
    ('182', ROW('Jämsä', 'Jämsä', 'Jämsä')),
    ('186', ROW('Järvenpää', 'Träskända', 'Järvenpää')),
    ('202', ROW('Kaarina', 'S:t Karins', 'Kaarina')),
    ('204', ROW('Kaavi', 'Kaavi', 'Kaavi')),
    ('205', ROW('Kajaani', 'Kajana', 'Kajaani')),
    ('208', ROW('Kalajoki', 'Kalajoki', 'Kalajoki')),
    ('211', ROW('Kangasala', 'Kangasala', 'Kangasala')),
    ('213', ROW('Kangasniemi', 'Kangasniemi', 'Kangasniemi')),
    ('214', ROW('Kankaanpää', 'Kankaanpää', 'Kankaanpää')),
    ('216', ROW('Kannonkoski', 'Kannonkoski', 'Kannonkoski')),
    ('217', ROW('Kannus', 'Kannus', 'Kannus')),
    ('218', ROW('Karijoki', 'Bötom', 'Karijoki')),
    ('224', ROW('Karkkila', 'Högfors', 'Karkkila')),
    ('226', ROW('Karstula', 'Karstula', 'Karstula')),
    ('230', ROW('Karvia', 'Karvia', 'Karvia')),
    ('231', ROW('Kaskinen', 'Kaskö', 'Kaskinen')),
    ('232', ROW('Kauhajoki', 'Kauhajoki', 'Kauhajoki')),
    ('233', ROW('Kauhava', 'Kauhava', 'Kauhava')),
    ('235', ROW('Kauniainen', 'Grankulla', 'Kauniainen')),
    ('236', ROW('Kaustinen', 'Kaustby', 'Kaustinen')),
    ('239', ROW('Keitele', 'Keitele', 'Keitele')),
    ('240', ROW('Kemi', 'Kemi', 'Kemi')),
    ('241', ROW('Keminmaa', 'Keminmaa', 'Keminmaa')),
    ('244', ROW('Kempele', 'Kempele', 'Kempele')),
    ('245', ROW('Kerava', 'Kervo', 'Kerava')),
    ('249', ROW('Keuruu', 'Keuru', 'Keuruu')),
    ('250', ROW('Kihniö', 'Kihniö', 'Kihniö')),
    ('256', ROW('Kinnula', 'Kinnula', 'Kinnula')),
    ('257', ROW('Kirkkonummi', 'Kyrkslätt', 'Kirkkonummi')),
    ('260', ROW('Kitee', 'Kides', 'Kitee')),
    ('261', ROW('Kittilä', 'Kittilä', 'Kittilä')),
    ('263', ROW('Kiuruvesi', 'Kiuruvesi', 'Kiuruvesi')),
    ('265', ROW('Kivijärvi', 'Kivijärvi', 'Kivijärvi')),
    ('271', ROW('Kokemäki', 'Kumo', 'Kokemäki')),
    ('272', ROW('Kokkola', 'Karleby', 'Kokkola')),
    ('273', ROW('Kolari', 'Kolari', 'Kolari')),
    ('275', ROW('Konnevesi', 'Konnevesi', 'Konnevesi')),
    ('276', ROW('Kontiolahti', 'Kontiolax', 'Kontiolahti')),
    ('280', ROW('Korsnäs', 'Korsnäs', 'Korsnäs')),
    ('284', ROW('Koski Tl', 'Koskis', 'Koski Tl')),
    ('285', ROW('Kotka', 'Kotka', 'Kotka')),
    ('286', ROW('Kouvola', 'Kouvola', 'Kouvola')),
    ('287', ROW('Kristiinankaupunki', 'Kristinestad', 'Kristinestad')),
    ('288', ROW('Kruunupyy', 'Kronoby', 'Kronoby')),
    ('290', ROW('Kuhmo', 'Kuhmo', 'Kuhmo')),
    ('291', ROW('Kuhmoinen', 'Kuhmois', 'Kuhmoinen')),
    ('295', ROW('Kumlinge', 'Kumlinge', 'Kumlinge')),
    ('297', ROW('Kuopio', 'Kuopio', 'Kuopio')),
    ('300', ROW('Kuortane', 'Kuortane', 'Kuortane')),
    ('301', ROW('Kurikka', 'Kurikka', 'Kurikka')),
    ('304', ROW('Kustavi', 'Gustavs', 'Kustavi')),
    ('305', ROW('Kuusamo', 'Kuusamo', 'Kuusamo')),
    ('309', ROW('Outokumpu', 'Outokumpu', 'Outokumpu')),
    ('312', ROW('Kyyjärvi', 'Kyyjärvi', 'Kyyjärvi')),
    ('316', ROW('Kärkölä', 'Kärkölä', 'Kärkölä')),
    ('317', ROW('Kärsämäki', 'Kärsämäki', 'Kärsämäki')),
    ('318', ROW('Kökar', 'Kökar', 'Kökar')),
    ('320', ROW('Kemijärvi', 'Kemijärvi', 'Kemijärvi')),
    ('322', ROW('Kemiönsaari', 'Kimitoön', 'Kimitoön')),
    ('398', ROW('Lahti', 'Lahtis', 'Lahti')),
    ('399', ROW('Laihia', 'Laihela', 'Laihia')),
    ('400', ROW('Laitila', 'Letala', 'Laitila')),
    ('402', ROW('Lapinlahti', 'Lapinlahti', 'Lapinlahti')),
    ('403', ROW('Lappajärvi', 'Lappajärvi', 'Lappajärvi')),
    ('405', ROW('Lappeenranta', 'Villmanstrand', 'Lappeenranta')),
    ('407', ROW('Lapinjärvi', 'Lappträsk', 'Lapinjärvi')),
    ('408', ROW('Lapua', 'Lappo', 'Lapua')),
    ('410', ROW('Laukaa', 'Laukas', 'Laukaa')),
    ('416', ROW('Lemi', 'Lemi', 'Lemi')),
    ('417', ROW('Lemland', 'Lemland', 'Lemland')),
    ('418', ROW('Lempäälä', 'Lempäälä', 'Lempäälä')),
    ('420', ROW('Leppävirta', 'Leppävirta', 'Leppävirta')),
    ('421', ROW('Lestijärvi', 'Lestijärvi', 'Lestijärvi')),
    ('422', ROW('Lieksa', 'Lieksa', 'Lieksa')),
    ('423', ROW('Lieto', 'Lundo', 'Lieto')),
    ('425', ROW('Liminka', 'Limingo', 'Liminka')),
    ('426', ROW('Liperi', 'Libelits', 'Liperi')),
    ('430', ROW('Loimaa', 'Loimaa', 'Loimaa')),
    ('433', ROW('Loppi', 'Loppi', 'Loppi')),
    ('434', ROW('Loviisa', 'Lovisa', 'Loviisa')),
    ('435', ROW('Luhanka', 'Luhanka', 'Luhanka')),
    ('436', ROW('Lumijoki', 'Lumijoki', 'Lumijoki')),
    ('438', ROW('Lumparland', 'Lumparland', 'Lumparland')),
    ('440', ROW('Luoto', 'Larsmo', 'Larsmo')),
    ('441', ROW('Luumäki', 'Luumäki', 'Luumäki')),
    ('444', ROW('Lohja', 'Lojo', 'Lohja')),
    ('445', ROW('Parainen', 'Pargas', 'Pargas')),
    ('475', ROW('Maalahti', 'Malax', 'Malax')),
    ('478', ROW('Maarianhamina - Mariehamn', 'Mariehamn', 'Mariehamn')),
    ('480', ROW('Marttila', 'S:t Mårtens', 'Marttila')),
    ('481', ROW('Masku', 'Masku', 'Masku')),
    ('483', ROW('Merijärvi', 'Merijärvi', 'Merijärvi')),
    ('484', ROW('Merikarvia', 'Sastmola', 'Merikarvia')),
    ('489', ROW('Miehikkälä', 'Miehikkälä', 'Miehikkälä')),
    ('491', ROW('Mikkeli', 'S:t Michel', 'Mikkeli')),
    ('494', ROW('Muhos', 'Muhos', 'Muhos')),
    ('495', ROW('Multia', 'Multia', 'Multia')),
    ('498', ROW('Muonio', 'Muonio', 'Muonio')),
    ('499', ROW('Mustasaari', 'Korsholm', 'Korsholm')),
    ('500', ROW('Muurame', 'Muurame', 'Muurame')),
    ('503', ROW('Mynämäki', 'Virmo', 'Mynämäki')),
    ('504', ROW('Myrskylä', 'Mörskom', 'Myrskylä')),
    ('505', ROW('Mäntsälä', 'Mäntsälä', 'Mäntsälä')),
    ('507', ROW('Mäntyharju', 'Mäntyharju', 'Mäntyharju')),
    ('508', ROW('Mänttä-Vilppula', 'Mänttä-Vilppula', 'Mänttä-Vilppula')),
    ('529', ROW('Naantali', 'Nådendal', 'Naantali')),
    ('531', ROW('Nakkila', 'Nakkila', 'Nakkila')),
    ('535', ROW('Nivala', 'Nivala', 'Nivala')),
    ('536', ROW('Nokia', 'Nokia', 'Nokia')),
    ('538', ROW('Nousiainen', 'Nousis', 'Nousiainen')),
    ('541', ROW('Nurmes', 'Nurmes', 'Nurmes')),
    ('543', ROW('Nurmijärvi', 'Nurmijärvi', 'Nurmijärvi')),
    ('545', ROW('Närpiö', 'Närpes', 'Närpes')),
    ('560', ROW('Orimattila', 'Orimattila', 'Orimattila')),
    ('561', ROW('Oripää', 'Oripää', 'Oripää')),
    ('562', ROW('Orivesi', 'Orivesi', 'Orivesi')),
    ('563', ROW('Oulainen', 'Oulainen', 'Oulainen')),
    ('564', ROW('Oulu', 'Uleåborg', 'Oulu')),
    ('576', ROW('Padasjoki', 'Padasjoki', 'Padasjoki')),
    ('577', ROW('Paimio', 'Pemar', 'Paimio')),
    ('578', ROW('Paltamo', 'Paltamo', 'Paltamo')),
    ('580', ROW('Parikkala', 'Parikkala', 'Parikkala')),
    ('581', ROW('Parkano', 'Parkano', 'Parkano')),
    ('583', ROW('Pelkosenniemi', 'Pelkosenniemi', 'Pelkosenniemi')),
    ('584', ROW('Perho', 'Perho', 'Perho')),
    ('588', ROW('Pertunmaa', 'Pertunmaa', 'Pertunmaa')),
    ('592', ROW('Petäjävesi', 'Petäjävesi', 'Petäjävesi')),
    ('593', ROW('Pieksämäki', 'Pieksämäki', 'Pieksämäki')),
    ('595', ROW('Pielavesi', 'Pielavesi', 'Pielavesi')),
    ('598', ROW('Pietarsaari', 'Jakobstad', 'Jakobstad')),
    ('599', ROW('Pedersören kunta', 'Pedersöre', 'Pedersöre')),
    ('601', ROW('Pihtipudas', 'Pihtipudas', 'Pihtipudas')),
    ('604', ROW('Pirkkala', 'Birkala', 'Pirkkala')),
    ('607', ROW('Polvijärvi', 'Polvijärvi', 'Polvijärvi')),
    ('608', ROW('Pomarkku', 'Påmark', 'Pomarkku')),
    ('609', ROW('Pori', 'Björneborg', 'Pori')),
    ('611', ROW('Pornainen', 'Borgnäs', 'Pornainen')),
    ('614', ROW('Posio', 'Posio', 'Posio')),
    ('615', ROW('Pudasjärvi', 'Pudasjärvi', 'Pudasjärvi')),
    ('616', ROW('Pukkila', 'Pukkila', 'Pukkila')),
    ('619', ROW('Punkalaidun', 'Punkalaidun', 'Punkalaidun')),
    ('620', ROW('Puolanka', 'Puolanka', 'Puolanka')),
    ('623', ROW('Puumala', 'Puumala', 'Puumala')),
    ('624', ROW('Pyhtää', 'Pyttis', 'Pyhtää')),
    ('625', ROW('Pyhäjoki', 'Pyhäjoki', 'Pyhäjoki')),
    ('626', ROW('Pyhäjärvi', 'Pyhäjärvi', 'Pyhäjärvi')),
    ('630', ROW('Pyhäntä', 'Pyhäntä', 'Pyhäntä')),
    ('631', ROW('Pyhäranta', 'Pyhäranta', 'Pyhäranta')),
    ('635', ROW('Pälkäne', 'Pälkäne', 'Pälkäne')),
    ('636', ROW('Pöytyä', 'Pöytyä', 'Pöytyä')),
    ('638', ROW('Porvoo', 'Borgå', 'Porvoo')),
    ('678', ROW('Raahe', 'Brahestad', 'Raahe')),
    ('680', ROW('Raisio', 'Reso', 'Raisio')),
    ('681', ROW('Rantasalmi', 'Rantasalmi', 'Rantasalmi')),
    ('683', ROW('Ranua', 'Ranua', 'Ranua')),
    ('684', ROW('Rauma', 'Raumo', 'Rauma')),
    ('686', ROW('Rautalampi', 'Rautalampi', 'Rautalampi')),
    ('687', ROW('Rautavaara', 'Rautavaara', 'Rautavaara')),
    ('689', ROW('Rautjärvi', 'Rautjärvi', 'Rautjärvi')),
    ('691', ROW('Reisjärvi', 'Reisjärvi', 'Reisjärvi')),
    ('694', ROW('Riihimäki', 'Riihimäki', 'Riihimäki')),
    ('697', ROW('Ristijärvi', 'Ristijärvi', 'Ristijärvi')),
    ('698', ROW('Rovaniemi', 'Rovaniemi', 'Rovaniemi')),
    ('700', ROW('Ruokolahti', 'Ruokolax', 'Ruokolahti')),
    ('702', ROW('Ruovesi', 'Ruovesi', 'Ruovesi')),
    ('704', ROW('Rusko', 'Rusko', 'Rusko')),
    ('707', ROW('Rääkkylä', 'Rääkkylä', 'Rääkkylä')),
    ('710', ROW('Raasepori', 'Raseborg', 'Raasepori')),
    ('729', ROW('Saarijärvi', 'Saarijärvi', 'Saarijärvi')),
    ('732', ROW('Salla', 'Salla', 'Salla')),
    ('734', ROW('Salo', 'Salo', 'Salo')),
    ('736', ROW('Saltvik', 'Saltvik', 'Saltvik')),
    ('738', ROW('Sauvo', 'Sagu', 'Sauvo')),
    ('739', ROW('Savitaipale', 'Savitaipale', 'Savitaipale')),
    ('740', ROW('Savonlinna', 'Nyslott', 'Savonlinna')),
    ('742', ROW('Savukoski', 'Savukoski', 'Savukoski')),
    ('743', ROW('Seinäjoki', 'Seinäjoki', 'Seinäjoki')),
    ('746', ROW('Sievi', 'Sievi', 'Sievi')),
    ('747', ROW('Siikainen', 'Siikais', 'Siikainen')),
    ('748', ROW('Siikajoki', 'Siikajoki', 'Siikajoki')),
    ('749', ROW('Siilinjärvi', 'Siilinjärvi', 'Siilinjärvi')),
    ('751', ROW('Simo', 'Simo', 'Simo')),
    ('753', ROW('Sipoo', 'Sibbo', 'Sipoo')),
    ('755', ROW('Siuntio', 'Sjundeå', 'Siuntio')),
    ('758', ROW('Sodankylä', 'Sodankylä', 'Sodankylä')),
    ('759', ROW('Soini', 'Soini', 'Soini')),
    ('761', ROW('Somero', 'Somero', 'Somero')),
    ('762', ROW('Sonkajärvi', 'Sonkajärvi', 'Sonkajärvi')),
    ('765', ROW('Sotkamo', 'Sotkamo', 'Sotkamo')),
    ('766', ROW('Sottunga', 'Sottunga', 'Sottunga')),
    ('768', ROW('Sulkava', 'Sulkava', 'Sulkava')),
    ('771', ROW('Sund', 'Sund', 'Sund')),
    ('777', ROW('Suomussalmi', 'Suomussalmi', 'Suomussalmi')),
    ('778', ROW('Suonenjoki', 'Suonenjoki', 'Suonenjoki')),
    ('781', ROW('Sysmä', 'Sysmä', 'Sysmä')),
    ('783', ROW('Säkylä', 'Säkylä', 'Säkylä')),
    ('785', ROW('Vaala', 'Vaala', 'Vaala')),
    ('790', ROW('Sastamala', 'Sastamala', 'Sastamala')),
    ('791', ROW('Siikalatva', 'Siikalatva', 'Siikalatva')),
    ('831', ROW('Taipalsaari', 'Taipalsaari', 'Taipalsaari')),
    ('832', ROW('Taivalkoski', 'Taivalkoski', 'Taivalkoski')),
    ('833', ROW('Taivassalo', 'Tövsala', 'Taivassalo')),
    ('834', ROW('Tammela', 'Tammela', 'Tammela')),
    ('837', ROW('Tampere', 'Tammerfors', 'Tampere')),
    ('844', ROW('Tervo', 'Tervo', 'Tervo')),
    ('845', ROW('Tervola', 'Tervola', 'Tervola')),
    ('846', ROW('Teuva', 'Östermark', 'Teuva')),
    ('848', ROW('Tohmajärvi', 'Tohmajärvi', 'Tohmajärvi')),
    ('849', ROW('Toholampi', 'Toholampi', 'Toholampi')),
    ('850', ROW('Toivakka', 'Toivakka', 'Toivakka')),
    ('851', ROW('Tornio', 'Torneå', 'Tornio')),
    ('853', ROW('Turku', 'Åbo', 'Turku')),
    ('854', ROW('Pello', 'Pello', 'Pello')),
    ('857', ROW('Tuusniemi', 'Tuusniemi', 'Tuusniemi')),
    ('858', ROW('Tuusula', 'Tusby', 'Tuusula')),
    ('859', ROW('Tyrnävä', 'Tyrnävä', 'Tyrnävä')),
    ('886', ROW('Ulvila', 'Ulvsby', 'Ulvila')),
    ('887', ROW('Urjala', 'Urjala', 'Urjala')),
    ('889', ROW('Utajärvi', 'Utajärvi', 'Utajärvi')),
    ('890', ROW('Utsjoki', 'Utsjoki', 'Utsjoki')),
    ('892', ROW('Uurainen', 'Uurainen', 'Uurainen')),
    ('893', ROW('Uusikaarlepyy', 'Nykarleby', 'Nykarleby')),
    ('895', ROW('Uusikaupunki', 'Nystad', 'Uusikaupunki')),
    ('905', ROW('Vaasa', 'Vasa', 'Vaasa')),
    ('908', ROW('Valkeakoski', 'Valkeakoski', 'Valkeakoski')),
    ('915', ROW('Varkaus', 'Varkaus', 'Varkaus')),
    ('918', ROW('Vehmaa', 'Vemo', 'Vehmaa')),
    ('921', ROW('Vesanto', 'Vesanto', 'Vesanto')),
    ('922', ROW('Vesilahti', 'Vesilahti', 'Vesilahti')),
    ('924', ROW('Veteli', 'Vetil', 'Veteli')),
    ('925', ROW('Vieremä', 'Vieremä', 'Vieremä')),
    ('927', ROW('Vihti', 'Vichtis', 'Vihti')),
    ('931', ROW('Viitasaari', 'Viitasaari', 'Viitasaari')),
    ('934', ROW('Vimpeli', 'Vindala', 'Vimpeli')),
    ('935', ROW('Virolahti', 'Vederlax', 'Virolahti')),
    ('936', ROW('Virrat', 'Virdois', 'Virrat')),
    ('941', ROW('Vårdö', 'Vårdö', 'Vårdö')),
    ('946', ROW('Vöyri', 'Vörå', 'Vöyri')),
    ('976', ROW('Ylitornio', 'Övertorneå', 'Ylitornio')),
    ('977', ROW('Ylivieska', 'Ylivieska', 'Ylivieska')),
    ('980', ROW('Ylöjärvi', 'Ylöjärvi', 'Ylöjärvi')),
    ('981', ROW('Ypäjä', 'Ypäjä', 'Ypäjä')),
    ('989', ROW('Ähtäri', 'Etseri', 'Ähtäri')),
    ('992', ROW('Äänekoski', 'Äänekoski', 'Äänekoski'));

ALTER TABLE "aurora_ai_service"
    ADD COLUMN "provider" translatable_text NOT NULL DEFAULT ROW('Tuntematon', 'Okänd', 'Unknown'),
    ADD COLUMN "name" translatable_text NOT NULL DEFAULT ROW('Tuntematon', 'Okänd', 'Unknown'),
    ADD COLUMN "description" translatable_text NOT NULL DEFAULT ROW('Tuntematon', 'Okänd', 'Unknown'),
    ADD COLUMN "type" int NOT NULL REFERENCES aurora_ai_service_type(id) DEFAULT 1,
    ADD COLUMN "location" text NOT NULL REFERENCES aurora_ai_service_location(code) DEFAULT '-1',
    ADD COLUMN "link" translatable_text;

CREATE TABLE "attribute_names" (
    "attribute" text,
    "name" translatable_text NOT NULL,
    PRIMARY KEY ("attribute")
);

INSERT INTO attribute_names
VALUES
    ('age', ROW('Ikä', 'Ålder', 'Age')),
    ('life_situation_meters', ROW('Elämäntilannemittari', 'Elämäntilannemittari', 'Life situation meters')),
    ('municipality_code', ROW('Kunta', 'Kommun', 'Municipality'));

UPDATE aurora_ai_service SET provider = ROW('Oikeusministeriö', 'Justitieministeriet', 'Ministry of Justice'), name = ROW('Lausuntopalvelu.fi', 'Utlåtande.fi', 'Lausuntopalvelu.fi'), description = ROW('Lausuntopalvelu.fi tarjoaa mahdollisuuden pyytää ja antaa lausuntoja sähköisesti. Kaikki julkishallinnon viranomaiset voivat julkaista lausuntopyyntöjä palvelussa. Lausuntoja saavat antaa kaikki organisaatiot ja kansalaiset.', 'Utlåtande.fi erbjuder möjligheten att be om och ge utlåtanden elektroniskt. Alla myndigheter inom offentlig förvaltning kan publicera utlåtandebegäran i tjänsten. Alla organisationer och medborgare får lämna utlåtanden.', ''), link = ROW('https://www.lausuntopalvelu.fi/FI', 'https://www.lausuntopalvelu.fi/SV', 'https://www.lausuntopalvelu.fi/EN') WHERE ptv_service_channel_id = '5894b8d5-a7be-47f2-8474-8f476a933e94';
UPDATE aurora_ai_service SET provider = ROW('Väestöliitto ry', 'Befolkningsförbundet rf', 'Väestöliitto ry'), name = ROW('Poikien Puhelimen chat', 'Pojkarnas telefons chatt', 'Poikien Puhelin chat'), description = ROW(E'Poikien Puhelimen chat on tarkoitettu pojille ja nuorille miehille, sukupuolen moninaisuus huomioiden.\n\nPalvelussa vastaa aikuinen, Väestöliiton miespuolinen työntekijä, joka on perehtynyt poikien maailmaan liittyviin asioihin.\n\nSinun ei tarvitse kertoa itsestäsi mitään, mitä et halua.\n\nKunnioitamme yksityisyyttäsi ja haluamme tarjota turvallisen ja luottamuksellisen tilan keskustelulle.\n\nKanssamme voit jutella mistä tahansa sinulle tärkeästä aiheesta, josta kaipaat enemmän tietoa tai joka sinua askarruttaa. Olet tervetullut palveluumme sellaisena kuin olet, riippumatta taustastasi. Olemme täällä sinua varten!\n\nChattiin pääset klikkaamalla "Siirry verkkoasiointiin"-painiketta, joka vie sinut Poikien Puhelimen verkkosivulle.', E'Pojkarnas telefons chatt är avsedd för alla som identifierar sig som pojkar eller unga män, eller funderar på sin könsidentitet.\n\nI vår jour svarar alltid någon ur Pojkarnas telefons team. Vårt team består av anställda sakkunniga hos Befolkningsförbundet: vuxna män, som är insatta i frågor som berör pojkar och unga män och som är utbildade för jourarbetet.\n\nDu behöver inte berätta något du inte vill.\n\nVi respekterar din integritet och vill erbjuda ett tryggt och förtroendefullt utrymme att prata.\n\nMed oss kan du tala om de frågor som är viktiga för dig, som du behöver mer information om eller funderar över. Du är välkommen till våra tjänster precis som du är, oberoende av din bakgrund. Vi finns här för dig!\n\nDu hittar chatten genom att klicka på knappen "Siirry verkkoasiointiin" som tar dig till Pojkarnas telefons webbplats.', ''), link = ROW('https://www.vaestoliitto.fi/poikien-puhelin/', 'https://www.vaestoliitto.fi/sv/pojkarnas-telefon/', 'https://www.vaestoliitto.fi/en/poikien-puhelin/') WHERE ptv_service_channel_id = '743c59c6-c41a-4973-88ae-3d5ae4e4ec1c';
UPDATE aurora_ai_service SET provider = ROW('Palveluntarjoaja', 'Tjänsteleverantör', 'Provider'), name = ROW('Testipalvelu 1', 'Testtjänst 1', 'Test service 1'), description = ROW('Testipalvelun 1 kuvaus.', 'Beskrivning av testtjänst 1.', 'Description of test service 1.') WHERE ptv_service_channel_id = 'f4eda39d-92ba-40cd-ae4a-a524e586969f';
UPDATE aurora_ai_service SET provider = ROW('Palveluntarjoaja', 'Tjänsteleverantör', 'Provider'), name = ROW('Testipalvelu 2', 'Testtjänst 2', 'Test service 2'), description = ROW('Testipalvelun 2 kuvaus.', 'Beskrivning av testtjänst 2.', 'Description of test service 2.') WHERE ptv_service_channel_id = '0ba11195-de64-43b3-af64-41aba7285364';
