default:
  db_host_routing: ''
  db_name: service_recommender
  db_port: '5432'
  db_api_user: service_recommender_api
  db_loader_user: service_recommender_loader
  drone_token_secret_name: drone_token
  drone_base_url: https://drone.tools.cloud.dvv.fi/api/repos/AAI/core-components
  drone_master_branch: master
  region: eu-west-1
  services_db_table: service_recommender.service
  service_vectors_db_table: service_recommender.service_vectors
  service_channels_db_table: service_recommender.service_channel
  require_api_auth: 'true'
  log_level: info
  log_requests: 'true'
  ptv_url_prefix: https://api.palvelutietovaranto.suomi.fi
  ptv_service_url_suffix: /api/v11/Service
  ptv_service_list_url_suffix: /api/v11/Service/list
  ptv_service_channel_url_suffix: /api/v11/ServiceChannel/
  ptv_service_channel_list_url_suffix: /api/v11/ServiceChannel/list
  ptv_service_collection_url_suffix: /api/v11/ServiceCollection
  municipality_file: resources/municipality_codes.json
  municipality_source_url: https://koodistot.suomi.fi/codelist-api/api/v1/coderegistries/jhs/codeschemes/kunta_1_20210101/?format=json&embedCodes=true&embedExtensions=true&embedMembers=true&expand=extension,member,codeScheme,code,memberValue,codeRegistry,organization,valueType,externalReference,propertyType&downloadFile=false&pretty
  service_class_file: resources/service_classes.json
  target_group_file: resources/filterable_target_groups.json
  funding_type_file: resources/funding_types.json
  municipality_region_mapping_file: resources/municipality_to_region.csv
  municipality_hospital_district_mapping_file: resources/municipality_to_hospital_district.csv
  wellbeing_service_county_codes_file: resources/wellbeing_service_county_codes.csv
  municipality_to_wellbeing_service_county_codes_mapping_file: resources/municipality_to_wellbeing_service_county_codes.csv
  services_key: services.json.xz
  service_vector_key: services_extended_20221122.csv
  service_channels_key: service_channels.json.xz
  use_service_locations: 'true'
  load_fasttext_from_s3: 'true'
  fasttext_download_dir: /tmp/aai-fasttext-download
  fasttext_s3_directory: fasttext
  fasttext_model_file: 2022-06-07-ptv.bin
  fasttext_embeddings_file: 2022-06-07-ptv-embeddings.pkl
  xgboost_model_file: 2022-09-20-xgb-reranker.json
  ptv_sentence_embeddings_path: embeddings/sentence_embeddings.pkl.npy
  ptv_term_embeddings_path: embeddings/ptv_term_embeddings.pkl.npy
  feature_flags: ui_search attributes_metadata_api translate_api
  service_host: ''
  service_recommender_api_port: '6000'
  service_recommender_api_host: 0.0.0.0
  service_recommender_api_workers: '3'
  service_recommender_api_worker_class: gevent
  service_recommender_api_timeout: '95'
  service_recommender_api_worker_tmp_dir: /tmp
  profile_management_api_port: '7000'
  profile_management_api_url: http://profile-management-api
  profile_management_recommender_api_key: ''
local:
  db_host_routing: localhost
  db_port: '5432'
  db_password: dummy
  db_api_user: service_recommender_test
  db_loader_user: service_recommender_test
  service_recommender_api_port: '5000'
  profile_management_api_port: '7000'
  profile_management_api_url: http://localhost:7000
  profile_management_recommender_api_key: test
  require_api_auth: 'false'
  load_fasttext_from_s3: 'false'
  log_level: debug
  log_requests: 'false'
localcluster:
  db_host_routing: service-recommender-db
  db_port: '5432'
  db_password: dummy
  db_api_user: service_recommender_test
  db_loader_user: service_recommender_test
  service_host: http://localhost:8080
  require_api_auth: 'false'
  load_fasttext_from_s3: 'false'
  profile_management_api_url: http://profile-management-api:7000
  profile_management_recommender_api_key: test
  services_bucket: service-recommender-dev
  service_recommender_api_workers: '3'
  log_level: debug
localunittest:
  service_host: https://unit-test-host
  services_bucket: dummybucket
  db_password: dummy
  db_host_routing: localhost
  db_api_user: service_recommender_test
  db_loader_user: service_recommender_test
  use_service_locations: 'false'
  load_fasttext_from_s3: 'false'
